version: '3.1'
services:
  app1:
    build: .

  app2:
    build: .

  nginx-proxy:
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
